// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0D7YSKplbCY3QY3HAr5qWaGz7v2qnyBo',
    appId: '1:384548972165:web:d4fd476783d9dc59feabec',
    messagingSenderId: '384548972165',
    projectId: 'solutions-challenge-cf8f8',
    authDomain: 'solutions-challenge-cf8f8.firebaseapp.com',
    storageBucket: 'solutions-challenge-cf8f8.appspot.com',
    measurementId: 'G-CZY7CGM8T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACL5RlTdemcTxIvgPTILu86mYluvj_To',
    appId: '1:384548972165:android:3ff064a83488042afeabec',
    messagingSenderId: '384548972165',
    projectId: 'solutions-challenge-cf8f8',
    storageBucket: 'solutions-challenge-cf8f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT87Zx_mQNogeV0RN5QHf8hLVVxlW94KA',
    appId: '1:384548972165:ios:1f5487aa2a07ca2ffeabec',
    messagingSenderId: '384548972165',
    projectId: 'solutions-challenge-cf8f8',
    storageBucket: 'solutions-challenge-cf8f8.appspot.com',
    iosClientId: '384548972165-hif7pfvvj8k6acgao4nlaurdoaoe1sof.apps.googleusercontent.com',
    iosBundleId: 'com.example.myflutterproject',
  );
}
